### ISSUE TITLE
Connection to protected services

### ISSUE THREAD

**Issue by LukeGIS** [geopython/MetaSearch#65]
Hi,
is it possible to connect protected services by access credentials (or services on server protected by user name & password) with MetaSearch?
I can load the same services with the "Add WMS button".
When I try to connect this kind of services, MetaSearch give me a connection errors....  ....401 - Unauthorized: Access is denied due to invalid credentials..... but I can not enter credentials.
To riproduce the problem you can try to load "Arpa Piemonte - Ortofoto AGEA 2009 - Provincia di Alessandria - (accesso riservato)" (search by keywords "AGEA (accesso riservato)") on our CSW catalog: http://webgis.arpa.piemonte.it/geoportalserver_arpa/csw?
How can solve this issue?
Many Thanks
Luca

**Comment by tomkralidis** [comment]
cc @geopython/metasearch 

@LukeGIS thanks for the info.  This is rooted in MetaSearch doing it's **own** GetCapabilities as a means to check/verify that the WMS/WMTS/WFS/WCS is actually valid, before passing to the appropriate QGIS WMS/WMTS/WFS/WCS dialog.

Options:
- enhance MetaSearch to support username/password to support authentication.  OWSLib (the underlying library doing the heavy lifting) supports authentication.  We would want to ensure if this is the case that when the WMS/WMTS/WFS/WCS dialog is then opened, the username/password is passed transparently so the user does not have to enter this information multiple times
- remove the WMS/WMTS/WFS/WCS `GetCapabilities` verification in MetaSearch and simply pass the URL on to the appropriate dialogue.  This pushes potential errors to the dialogue, which can be good (checking goes on in one place with one workflow) or bad (indirect to this particular issue, but elevated amount of errors in the dialogues, which may be a moot point since this would otherwise happen in MetaSearch proper anyway)

Comments?  This issue (for different reasons) has come up a few times in the past.

**Comment by LukeGIS** [comment]
Hi Tom, thanks for your answer!

In the short term is it possible to try removing the WMS / WMTS / WFS / WCS GetCapabilities verification in MetaSearch and simply pass the URL on to the appropriate dialogue?
In my opinion the Qgis standard control could be enough, and in any case the user is informed if there is some error in the WMS connection.

Another solution in mid term could be to allow the user to choose if use validation or not (ie in the metasearch option dialog) or working on credential management and communication between metasearch and QGIS.

Many thanks.

Luca

**Comment by tomkralidis** [comment]
@LukeGIS thanks for the info.  FYI I've started discussion on this in qgis-developer at http://lists.osgeo.org/pipermail/qgis-developer/2014-August/034415.html, and leaning towards lifting this from MetaSearch unless there are objections.

**Comment by tomkralidis** [comment]
@LukeGIS this is now fixed in master.  Thanks for the feedback.
