### ISSUE TITLE
Connection Error: Mismatched tag: line 57, column 3

### ISSUE THREAD

**Issue by lmenard** [geopython/MetaSearch#68]
Hi,
I've installed MetaSearch on a QGIS 2.6.0 Brighton on Mac OS 10.9.5.
I've been able to display some results (not for all) from default catalog collection.
I've tried to include mine with the URL as follow:
http://geocatalog.webservice-energy.org/geonetwork/srv/eng/csw

Though I can get successfully get the Information on the Service as well as the GetCapabilities response when I try to search for resources with or without keywords I get a pop-up window with the error as listed in the title of the email (see screenshot).

I did not see any reference to this error message in the GitHub.

 Thanks for your help.

Cheers,

Lionel
![capture d ecran 2014-11-04 a 12 45 49](https://cloud.githubusercontent.com/assets/9110605/4899087/2b37d07e-6418-11e4-8c4e-dd117e4b8ec7.png)

**Comment by tomkralidis** [comment]
@lmenard thanks for the report.  I am able to reproduce the error.  MetaSearch uses OWSLib 0.8.8.  There was an OWSLib bug that has since been fixed since OWSLib 0.8.10 (see https://github.com/geopython/OWSLib/commit/4e5e24840372028be2858c5c6897818bf6059282).  So the OWSLib depedency in QGIS needs to be updated.  I'll make this fix in QGIS by cutting a new MetaSearch release.  So options are:
- update your OWSLib in QGIS to 0.8.10 this will solve the issue until QGIS 2.6.1 is released
- update your MetaSearch in QGIS to 0.3.2 once it is released (I will do this week)
- wait for QGIS 2.6.1

**Comment by lmenard** [comment]
Hi Tom,
thanks a lot for the extra fast reply.
I think I will go for the simplest (at least for me) and wait for the next MetaSearch release.
Will I be notify of the new release in this thread or elsewhere ?

Thanks again.

Lionel

**Comment by tomkralidis** [comment]
@lmenard we usually tweet this.  I'll also ping this thread.

**Comment by tomkralidis** [comment]
@lmenard 0.3.2 is now at http://plugins.qgis.org/plugins/MetaSearch/. Can you try it out?

**Comment by lmenard** [comment]
I updated the plugin successfully (see screencast) did a stop start but the bug is still there...
![capture d ecran 2014-11-04 a 14 57 01](https://cloud.githubusercontent.com/assets/9110605/4900713/b0e4d53e-642a-11e4-99ad-0ed8da00d9be.png)

**Comment by tomkralidis** [comment]
This might be due to Python path settings where perhaps QGIS is picking up the OWSLib in 2.6 (0.8.8), not 0.8.10.  Can you try going into your QGIS and rename `python/owslib` to something like `python/owslib-old`?  This worked for me, and forced MetaSearch to use the OWSLib version bundled with MetaSearch instead.

**Comment by lmenard** [comment]
Done. Works fine (see screenshot). Any potential drawbacks due to this name changes ?

 Thanks a lot and "Bravo".

Lionel
![capture d ecran 2014-11-04 a 15 10 34](https://cloud.githubusercontent.com/assets/9110605/4900852/6b8d71ec-642c-11e4-9c69-18c7e6baf9f5.png)

**Comment by tomkralidis** [comment]
@lmenard thanks!  The renaming is a temporary workaround.  Once QGIS 2.6.1 / 2.8.0 is released this will be fully fixed.  For now the issue seems to be bound to a small edge case.
